/**
 * Generates a Caddyfile from the active services.
 *
 * Every service always gets a LAN block `<name>.<domainSuffix>` (e.g. .local)
 * with Caddy's internal CA. Services marked `public` additionally get a block
 * on the real public domain `<name>.<public.baseDomain>` with automatic HTTPS
 * (Let's Encrypt). Protected services get a `basic_auth` block in both.
 */
import {
  type ResolvedConfig,
  serviceFqdn,
  publicFqdn,
  isProtected,
  isPublic,
} from "../config.js";
import type { BasicAuth } from "../util/auth.js";

export function renderCaddyfile(cfg: ResolvedConfig, auth: BasicAuth | null): string {
  const out: string[] = [
    "# AUTO-GENERATED by home-stack. Edit home-stack.config.json and re-run setup.",
    "",
    "{",
    "\t# Global options",
    "\tadmin off",
  ];
  if (cfg.public.tlsEmail) out.push(`\temail ${cfg.public.tlsEmail}`);
  out.push("}", "");

  for (const svc of cfg.activeServices) {
    const upstream = `${svc.upstreamHost ?? svc.name}:${svc.upstreamPort}`;
    const gated = auth !== null && isProtected(cfg, svc.name);

    const body = (publicTls: boolean): string[] => {
      const lines: string[] = [];
      // LAN block uses internal CA; public block uses automatic Let's Encrypt.
      if (!publicTls && cfg.network.tls === "internal") lines.push("\ttls internal");
      if (gated && auth) {
        lines.push("\tbasic_auth {");
        lines.push(`\t\t${auth.username} ${auth.hash}`);
        lines.push("\t}");
      }
      lines.push(`\treverse_proxy ${upstream}`);
      return lines;
    };

    // Always: LAN hostname.
    out.push(`${serviceFqdn(svc, cfg)} {`, ...body(false), "}", "");

    // Optionally: public hostname.
    if (isPublic(cfg, svc.name) && cfg.public.baseDomain) {
      out.push(`${publicFqdn(cfg, svc.name)} {`, ...body(true), "}", "");
    }
  }

  return out.join("\n");
}
