/**
 * Generates a Caddyfile with one site block per active service, mapping
 * `<service>.<domainSuffix>` to the container upstream. TLS uses Caddy's
 * internal CA by default (browsers warn until you trust the root once).
 */
import type { ResolvedConfig } from "../config.js";
import { serviceFqdn } from "../config.js";

export function renderCaddyfile(cfg: ResolvedConfig): string {
  const blocks: string[] = [
    "# AUTO-GENERATED by home-stack. Edit home-stack.config.json and re-run setup.",
    "",
    "{",
    "\t# Global options",
    "\tadmin off",
    "}",
    "",
  ];

  for (const svc of cfg.activeServices) {
    const host = serviceFqdn(svc, cfg);
    const upstream = `${svc.upstreamHost ?? svc.name}:${svc.upstreamPort}`;
    blocks.push(`${host} {`);
    if (cfg.network.tls === "internal") {
      blocks.push("\ttls internal");
    }
    blocks.push(`\treverse_proxy ${upstream}`);
    blocks.push("}", "");
  }

  return blocks.join("\n");
}
