/**
 * Generates docker-compose.yml from the always-on core (Caddy + Portainer) plus
 * every installed catalog app. Serialized with the `yaml` package.
 */
import { stringify } from "yaml";
import { appContext, type ResolvedConfig } from "../config.js";
import { getApp } from "../catalog.js";
import { buildCustomService } from "./custom.js";

export function renderCompose(cfg: ResolvedConfig): string {
  const ctx = appContext(cfg);
  const tz = cfg.timezone;

  // --- Core infrastructure (always present) ---
  const services: Record<string, unknown> = {
    caddy: {
      image: "caddy:2-alpine",
      container_name: "caddy",
      restart: "unless-stopped",
      ports: ["80:80", "443:443"],
      networks: ["homestack"],
      volumes: [
        `${ctx.paths.config}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro`,
        `${ctx.paths.appdata}/caddy/data:/data`,
        `${ctx.paths.appdata}/caddy/config:/config`,
      ],
      environment: { TZ: tz },
    },
    portainer: {
      image: "portainer/portainer-ce:lts",
      container_name: "portainer",
      restart: "unless-stopped",
      command: ["-H", "unix:///var/run/docker.sock"],
      networks: ["homestack"],
      volumes: [
        "/var/run/docker.sock:/var/run/docker.sock:ro",
        `${ctx.paths.appdata}/portainer:/data`,
      ],
      environment: { TZ: tz },
    },
  };

  // --- Installed catalog apps ---
  for (const name of cfg.installed) {
    const app = getApp(name);
    if (!app) continue;
    services[app.name] = app.compose(ctx);
  }

  // --- User-defined custom apps ---
  for (const customApp of cfg.customApps) {
    services[customApp.name] = buildCustomService(customApp, ctx);
  }

  const doc = {
    name: "home-stack",
    services,
    networks: { homestack: { name: "homestack", driver: "bridge" } },
  };

  return (
    "# AUTO-GENERATED by home-stack. Manage apps with `home-stack install/uninstall`.\n" +
    stringify(doc, { lineWidth: 0 })
  );
}
