/**
 * Minimal Home Assistant configuration.yaml seed. Critically sets the
 * `http.trusted_proxies` block so HA accepts forwarded requests from Caddy,
 * otherwise the UI returns 400 behind the reverse proxy.
 */
export function renderHomeAssistantConfig(timezone: string): string {
  return `# AUTO-GENERATED by home-stack on first install. Safe to edit afterwards;
# home-stack will NOT overwrite this file once it exists.
default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies:
    # Docker bridge networks. Tighten to Caddy's container IP if you prefer.
    - 172.16.0.0/12
    - 127.0.0.1

homeassistant:
  name: Home
  time_zone: ${timezone}
  # Set unit_system / latitude / longitude via the onboarding UI.

# UI-managed automations/scenes/scripts.
automation: !include automations.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
`;
}
